version: '3.3'
services:
  php-apache-environment:
    build: ./
    container_name: php-apache
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8000:80
    #command: ["bash", "-c", "a2enmod rewrite"]
  mysql:
    image: mysql:5.7
    env_file: 
      - ./env/mysql.env
    ports:
      - 3306:3306